# Generated by Django 2.2.9 on 2020-08-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200722_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Выберите сообщество', max_length=200, unique=True, verbose_name='Сообщество'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Напишите здесь то, чем хотите поделиться..', verbose_name='Текст'),
        ),
    ]
