# Generated by Django 2.2.9 on 2020-08-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200818_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, error_messages={'empty': '5678', 'invalid': 'Загружаемый файл должен быть изображением', 'invalid_image': 'Попытка загрузки некорректного файла изображения', 'missing': '1234', 'required': '0000'}, help_text='Добавьте красивую картинку', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
