# Generated by Django 2.2.9 on 2020-08-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, error_messages={'empty': '4', 'invalid': '1', 'invalid_image': '2', 'missing': '3', 'required': '5'}, help_text='Добавьте красивую картинку', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
